language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
  - ree
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: 1.8.7
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: rbx-18mode
      jdk: openjdk7
    - rvm: rbx-18mode
      jdk: oraclejdk7
    - rvm: rbx-18mode
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk6
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7
    - rvm: ree
      jdk: openjdk6
